---
title: 'STOR 455 Midterm 2'
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
  word_document: default
---

You can write your R code for STOR 455 midterm 2 here. There is no need to submit your work in this file, but you can keep this file for future reference.

```{r}
library(readr)
library(polynom)
library(car)
library(leaps)
library(tidyverse)
library(titanic)
library(Stat2Data)
```


```{r}
data("Diamonds2")
Dia = lm(TotalPrice~Color, data = Diamonds2)
anova(Dia)

Diamonds2$D=(Diamonds2$Color=="D")*1
Diamonds2$F=(Diamonds2$Color=="F")*1
Diamonds2$E=(Diamonds2$Color=="E")*1
Diamonds2$G=(Diamonds2$Color=="G")*1

tapply(Diamonds2$TotalPrice, Diamonds2$Color, mean)

9160.397-5568.798
```


```{r}
TPModel = lm(TotalPrice~Carat+I(Carat)^2, data = Diamonds2)

plot(TPModel, 1:4)
```

```{r}
Diamonds2$logtotalprice = log(Diamonds2$TotalPrice)
Diamonds2$logcarat = log(Diamonds2$Carat)

logmodel = lm(logtotalprice~logcarat, data = Diamonds2)

# Use hat values to find leverage
#hatvalues(logmodel)
```


```{r}
logmodelcubic = lm(logtotalprice~poly(logcarat,degree=3, raw=TRUE), data=Diamonds2)
anova(logmodel, logmodelcubic)
```

```{r}
logTPModel = lm(TotalPrice~logcarat+I(logcarat)^2, data = Diamonds2)

car = data.frame(logcarat = 1.2)

predict.lm(logTPModel, car, interval = "prediction", level = 0.95)
```


```{r}
depthmodel = lm(logtotalprice~Depth, Diamonds2)
rstandard(depthmodel)[2]
```

Wrong for 13 and 14 of midterm 2
```{r}
depth2ndorder = lm(logtotalprice ~ Depth+I(Depth^2)+logcarat+I(logcarat^2) + I(Depth*logcarat), data = Diamonds2)
DepthCarat = lm(logtotalprice~logcarat+Depth+I(logcarat^2)+I(Depth^2), data = Diamonds2)
Depth = lm(logtotalprice~logcarat+I(logcarat^2), data = Diamonds2)
anova(DepthCarat, depth2ndorder)
anova(Depth, depth2ndorder)
```

```{r}
pricemodel = lm(logtotalprice~logcarat*factor(Color), data = Diamonds2)
anova(pricemodel)
```