---
title: "STOR 455 Class 7 R Notebook"
output:
  html_document:
    df_print: paged
---


```{r warning=FALSE, message=FALSE}
library(Stat2Data)

data("LongJumpOlympics2016")
data("PalmBeach")
```


```{r}
GoldModel=lm(Gold~Year, data=LongJumpOlympics2016)

plot(Gold~Year, data=LongJumpOlympics2016)
abline(GoldModel)

points(LongJumpOlympics2016$Year[16],
       LongJumpOlympics2016$Gold[16],
       col = "red",
       pch = 16)

summary(GoldModel)
```


```{r}
# slight difference between the two because of the leverage
StanResidEst = GoldModel$resid/summary(GoldModel)$sigma

StanResidEst - rstandard(GoldModel)
```


```{r}
# 
# difference is 0 if we consider the leverage through hatvalues()
StanResid = GoldModel$resid/(summary(GoldModel)$sigma * sqrt(1-hatvalues(GoldModel)))

StanResid - rstandard(GoldModel)
```


```{r}
# For a dataset with n observations, a typical leverage is 2/n.
# For long jump data, there are 28 observations. Check leverages that are larger than 2 (mild) and 3 (large) times 2/28 for potential highly influential observations.
2*(2/28)
3*(2/28)
hatvalues(GoldModel)

# sum of leverages is 2.
sum(hatvalues(GoldModel))

# sorting leverages from high to low.
sort(hatvalues(GoldModel), decreasing = TRUE)

# Conclusion: Although Bob Beamon's jump is a very large outlier, it has a mild leverage and does not change the line by much.
```


```{r}
ElectionModel=lm(Buchanan~Bush,data=PalmBeach)
plot(Buchanan~Bush, data = PalmBeach)
abline(ElectionModel)
points(PalmBeach$Bush[50],
       PalmBeach$Buchanan[50],
       col = "red",
       pch = 16)
```


```{r}
# For a dataset with 67 observations, check leverages that are larger than 2 (mild) and 3 (large) times 2/67.
2*(2/67)
3*(2/67)
sort(hatvalues(ElectionModel), decreasing = TRUE)

# Conclusion: Although PALM BEACH county is a very large outlier, it has only a mild leverage. However, DADE county has a huge leverage. 

# General fact: Outliers in x have high leverages.

# Defines new variable inside of the dataframe
PalmBeach$Leverage = hatvalues(ElectionModel)

# selecting observations with high influence.
which(PalmBeach$Leverage >= 2*(2/67))

PalmBeach[c(6, 13, 16, 29, 50, 52),]

subset(PalmBeach, PalmBeach$Leverage >= 2*(2/67))

# same... 
# PalmBeach[which(PalmBeach$Leverage >= 2*2/length(ElectionModel$residuals))]
```

```{r}
# plotting the original data in blue, PALM BEACH removed data in green, and DADE removed in red
# PALM BEACH is a huge outlier but has mild leverage
# DADE has a huge leverage but is not an outlier
# They have similar effects in changing the line. 

plot(Buchanan~Bush,data=PalmBeach)
abline(ElectionModel, col="blue")

NoPalmBeach=subset(PalmBeach,County!="PALM BEACH")
ElectionModel_noPB=lm(Buchanan~Bush,data=NoPalmBeach)
abline(ElectionModel_noPB, col="green")
 
NoDade = subset(PalmBeach,County!="DADE")
ElectionModel_noD=lm(Buchanan~Bush,data=NoDade)
abline(ElectionModel_noD, col="red")
```

```{r}
# Cook's distance cooks.distance() is a measure that take both outliers and high leverage observations into account on their effects influencing the line.
sort(cooks.distance(ElectionModel), decreasing=TRUE)
s
# Look for observations that have Cook's distance higher than 0.5 (mild) and 1 (high).
plot(ElectionModel, 5)
abline(v=4/67, col="blue", lty = 3)
abline(v=6/67, col="blue", lty = 3)
```


```{r warning=FALSE, message=FALSE}
library(readr)
library(Stat2Data)
library(metRology) # for curve plotting
library(tidyr) # easy functions and syntax for creating tidy data

lego <- read_csv("lego.csv")
lego_under_800_pieces = subset(lego, Pieces < 800)

# Use source() to load an R function not in package.
source("CIPIPlot.R") 
```


```{r}
modlego = lm(Amazon_Price~Pieces, data=lego_under_800_pieces)
```


```{r}
# tranformation data a bit...
modlego2 = lm(Amazon_Price^(0.3)~Pieces, data=lego_under_800_pieces)

```
Amazon_Price^(3/10)=B0+B1*Pieces
Amazon_Price=(B0+B1*Pieces)^(10/3)

```{r}
```


```{r}
# Using tidyr to remove rows with nas.
dataframe_to_write = lego_under_800_pieces %>% drop_na('Pieces', 'Amazon_Price')
dataframe_to_write$Amazon_Price_transformed = dataframe_to_write$Amazon_Price^0.3

write.csv(dataframe_to_write, 
          file = "lego_under_800_pieces.csv", 
          row.names=FALSE
)
```


```{r}
# Display the Student's t distributions with various
# degrees of freedom and compare to the normal distribution

x <- seq(-4, 4, length=100)
hx <- dnorm(x)

degf <- c(1, 5, 15, 30)
colors <- c("red", "blue", "darkgreen", "gold", "black")
labels <- c("df=1", "df=5", "df=15", "df=30", "normal")

plot(x, hx, type="l", lty=2, xlab="x value",
  ylab="Density", main="Comparison of t Distributions")

for (i in 1:4){
  lines(x, dt(x,degf[i]), lwd=2, col=colors[i])
}

legend("topright", inset=.05, title="Distributions",
  labels, lwd=2, lty=c(1, 1, 1, 1, 2), col=colors)
```


```{r}
# Degree of freedom for t is 718-2=716.
qt(0.975, 716)

curve(
  dt.scaled(
    x, 
    716,
    mean = summary(modlego2)$coef[2,1],
    sd = summary(modlego2)$coef[2,2]
    ), 
  from = 0.00190, to = 0.00255,
  )


abline(
  v=c(
    qt.scaled(
      0.025, 
      716, 
      mean = summary(modlego2)$coef[2,1], 
      sd = summary(modlego2)$coef[2,2]
      ),
    qt.scaled(
      0.975, 
      716, 
      mean = summary(modlego2)$coef[2,1], 
      sd = summary(modlego2)$coef[2,2]
      )
    )
  )
```


```{r}
# Boundaries of confidence interval for slope
summary(modlego2)$coef[2,1]-qt(0.975, 716)*summary(modlego2)$coef[2,2]
summary(modlego2)$coef[2,1]+qt(0.975, 716)*summary(modlego2)$coef[2,2]
```


```{r}
# Use confint() to get the confidence interval from model
confint(modlego2, level=0.95)
```