---
title: "STOR 455 - Class 23 - R Notebook"
output:
  html_document:
    df_print: paged
---


```{r message=FALSE, warning=FALSE}
library(readr)

Exams4 <- read_csv("Exams4.csv")

Exams4
```


```{r}
# Plotting "Grade" distributions for each "Exam"
# Use tapply(variable1, variable2, function) to apply the "function" to each group of "variable 1" partitioned based on "variable 2"
means = tapply(Exams4$Grade, Exams4$Exam, mean)

tapply(Exams4$Grade, Exams4$Exam, mean)
tapply(Exams4$Grade, Exams4$Exam, sd)
tapply(Exams4$Grade, Exams4$Exam, length)

boxplot(Grade ~ Exam, data = Exams4)
points(means, col="red", pch=4)
```


```{r}
# SSE is the sum of squared differences from each point to its group mean (red cross).
# SSGroup is the sum of the squared difference from each group mean (red cross) to the grand mean (blue line) multiplied by its group size.
# SSTotal is the sum of squared differences from each point to grand mean (blue line).
# SSTotal=SSGroup+SSE
plot(Grade ~ Exam, data = Exams4)
points(means, col="red", pch=4)
abline(h = mean(Exams4$Grade), col = "blue")
```


```{r}
# Use aov() for comparing the group means. Are grades different among exams?
# Note here since "Exam" is coded in numbers 1 through 4, we need to use factor() to make it categorical.
amodG=aov(Grade~Exam, data=Exams4)
# There seems to be no statistically significant difference in grades among exams.
summary(amodG)
```


```{r}
# Checking ANOVA conditions
plot(amodG)
# Checking the constant variance condition
round(tapply(Exams4$Grade,Exams4$Exam,sd),2)
```


```{r}
# Another way to do ANOVA for group comparisons. Are students different in taking exams?
modS=aov(Grade~factor(Student), data = Exams4)
summary(modS)

plot(modS, 1:2)
round(tapply(Exams4$Grade,Exams4$Student,sd),2)
```


```{r}
# There are k=5 groups, so the df of t-statistic is n-k=20-5=15.
modS$df.residual
t_LSD = qt(1 - 0.05/2, modS$df.residual)

# Error variance estimate
MSE = summary(modS)[[1]][,3][2]

# The naive least significant difference. Grades from two students are regarded different if their means differ more from LSD.
LSD = t_LSD * sqrt(MSE)*sqrt(1/4 + 1/4)
LSD
```


```{r}
# The chance of making type I error with naive LSD can be about 40%!
1-(1-0.05)^10

# Using Bonferroni is OK.
1-(1-0.05/10)^10
```


```{r}
# Using Bonferroni correction to obtain the t quantile
t_bf = qt(1 - 0.05/10/2, modS$df.residual)

BSD = t_bf * sqrt(MSE)*sqrt(1/4 + 1/4)
BSD
```


```{r}
# Tukey's Honestly Significant Difference: valid while less conservative than Bonferroni.
HSD = qtukey(1-0.05, 5, modS$df.residual)/sqrt(2)* sqrt(MSE)*sqrt(1/4 + 1/4)
HSD
```


```{r}
# pairwise.t.test() for comparing group means. 
pairwise.t.test()

```

```{r}
# TukeyHSD() for comparing group means.
TukeyHSD() 
```

```{r warning=FALSE}
# Plotting Tukey's HSD confidence intervals
origpar = par()
par(mar=c(4,7,3,1))
hsd = TukeyHSD(modS)
plot(hsd, las=2)
par(origpar)
```