---
title: 'STOR 455 Exam 1'
output:
  word_document: default
  html_notebook: default
  pdf_document: default
  html_document:
    df_print: paged
---

You can write your R code for STOR 455 midterm 1 here. There is no need to submit your work in this file, but you can keep this file for future reference.

```{r}
library(Stat2Data)
library(leaps)
data("Fertility")

head(Fertility)
```


```{r}
Fertile = lm(Embryos~Age+LowAFC+MeanAFC+FSH+E2+MaxE2+MaxDailyGn+TotalGn+Oocytes, data = Fertility)
summary(Fertile)

#plot(Embryos~Age+LowAFC+MeanAFC+FSH+E2+MaxE2+MaxDailyGn+TotalGn+Oocytes, data = Fertility)
#abline(Fertile)

plot(Fertile, 1:2)
hist(Fertile$residuals)
```

```{r}
LM = lm(Embryos~MaxE2, data = Fertility)
summary(LM)
sqrt(0.1879)

cor(Fertility$Embryos, Fertility$MaxE2)
```



```{r}
all = regsubsets(Embryos~Age+LowAFC+MeanAFC+FSH+E2+MaxE2+MaxDailyGn+TotalGn+Oocytes, data = Fertility)
summary(all)

# Backward elimination
MSE = (summary(Fertile)$sigma)^2
step(Fertile, scale=MSE)

# Forward selection
none = lm(Embryos~1, data = Fertility)
step(none, scope = list(upper=Fertile), scale = MSE, direction = "forward")

# Stepwise regression
step(none, scope=list(upper=Fertile), scale = MSE)
```

```{r}
summary(Fertile)
```

```{r}
Resids = (Fertile$residuals)
#Resids

largest_resid = which(Resids < -9)

rstudent(Fertile)[largest_resid]
```


```{r}
sort(cooks.distance(Fertile), decreasing=TRUE)[1]
```


```{r}
Values = data.frame(Oocytes = 20, MaxE2 = 2000)
BestModel = lm(Embryos ~ Oocytes+MaxE2, data = Fertility)
predict.lm(BestModel, Values, interval = "prediction", level = 0.95)
```
